### ISSUE TITLE
Solicitud de Incorporación al proyecto

### ISSUE THREAD

**Issue by gus0117** [alecio87/devtech-podcast-web#1]
## Solicitud de incorporación.

Hola Emanuel soy Gustavo Ordoñez, te solicito incorporarme al proyecto 😁.

![image](https://media.giphy.com/media/13UZisxBxkjPwI/giphy.gif)

### Modificaciones que propongo

- Agregaré un nuevo asset para mi avatar de Avatar Maker y una descripción mia.
- Modificare una tarjeta para que quede tal cual así:

![image](https://user-images.githubusercontent.com/49104263/178356925-ea98bcf4-5131-4b24-8081-e06fef4d584c.png)

### Enlaces

- [Extención de google chrome](https://chrome.google.com/webstore/detail/avatar-maker/ofknlbikfofijlcjkfcihomkedmchfbn)

Saludos ✌️

**Comment by alecio87** [comment]
Solicitud Aprobada #1
Muy buena tu propuesta Gustavo, te asigno la tarjeta numero 1 para modificar. Excelente la extension
![image](https://user-images.githubusercontent.com/21963028/178364428-95f078ac-1a39-4e0c-9f72-c1e6d03fdb9b.png)

Saludo  Atte.  Emanuel Ibañes!!!
