### ISSUE TITLE
Solicitud nuevo integrante

### ISSUE THREAD

**Issue by mamanidario19** [alecio87/devtech-podcast-web#2]
## Presentación
Hola compañero! soy Dario te escribo para que me permitas agregar mi tarjeta en tu proyecto.

![image](https://media3.giphy.com/media/ZVik7pBtu9dNS/giphy.gif?cid=ecf05e47mab7sns7v0vihufesxo2wv4vkcdxe099wjnyvrjx&rid=giphy.gif&ct=g)

## Modificaciones futuras:
 * Agregar imagen de avatar.
 * Modificar index.html con mi descripción.
## Previsualización
![image](https://user-images.githubusercontent.com/32744941/178361136-e888ec93-c7e2-446e-9478-d2abf0ae2cb1.png)
 
Espero tu aprobación! saludos! 🙇‍♂️

**Comment by alecio87** [comment]
Solicitud Aprobada #2
Muy buena tu propuesta Dario, te asigno la tarjeta numero 3 para modificar. Excelente la extension
![image](https://user-images.githubusercontent.com/21963028/178364428-95f078ac-1a39-4e0c-9f72-c1e6d03fdb9b.png)

Saludo  Atte.  Emanuel Ibañes!!!
